### ISSUE TITLE
Node 0.10 crashes "Use of const in strict mode"

### ISSUE THREAD

**Issue by ksheedlo** [teambition/merge2#13]
I have an application that runs on Node 0.10. When we try to import this package it crashes with the following error:

```
/Users/ken/unpm-code/chameleon-ui/node_modules/merge2/index.js:9
const Stream = require('stream')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ken/unpm-code/chameleon-ui/node_modules/unitest/index.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

This crash is occurring because merge2 uses `const`, which behaves differently in node 0.10. Please consider adding a build step that compiles ES6 to ES5 for older versions of node at publish time.

**Comment by zensh** [comment]
Hi, I recommend using v1.0.x in Node v0.10. v1.1 has used ES6 that can't run in Node v0.10
