### ISSUE TITLE
0.3.3 with gulp-sass produces Error: Only readable stream can be merged.

### ISSUE THREAD

**Issue by parsnick** [teambition/merge2#3]
Trying to merge two streams, one of which has been piped through gulp-sass, produces `Error: Only readable stream can be merged.`

I had tried a few other gulp plugins and they all worked, so I first posted an issue to gulp-sass about this: dlmanning/gulp-sass#237 (includes sample code and repo)

But after looking into it further, the same code actually works fine if using merge2 <= 0.3.1 

With 0.3.2 I get:
```
[03:09:26] Using gulpfile /var/www/gulp-sass-merge2/gulpfile.js
[03:09:26] Starting 'default'...

/var/www/gulp-sass-merge2/node_modules/merge2/index.js:57
      if (stream._readableState.endEmitted) return next();
                               ^
TypeError: Cannot read property 'endEmitted' of undefined
    at pipe (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:57:32)
    at mergeStream (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:65:46)
    at next (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:47:7)
    at DestroyableTransform.onend (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:54:9)
    at DestroyableTransform.emit (events.js:117:20)
    at /var/www/gulp-sass-merge2/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:448:13)
```

And with 0.3.3, as per the linked issue:
```
[02:41:42] Using gulpfile /var/www/gulp-sass-merge2/gulpfile.js
[02:41:42] Starting 'default'...
[02:41:42] 'default' errored after 4.51 ms
[02:41:42] Error: Only readable stream can be merged.
    at pauseStreams (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:92:13)
    at addStream (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:29:25)
    at merge2 (/var/www/gulp-sass-merge2/node_modules/merge2/index.js:84:30)
    at Gulp.<anonymous> (/var/www/gulp-sass-merge2/gulpfile.js:9:9)
    at module.exports (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/gulp-sass-merge2/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
```

So now I'm not sure if there's a problem with this plugin, the gulp-sass plugin, or if for some reason they just don't play well together?

**Comment by zensh** [comment]
this problem is cause  by https://github.com/dominictarr/map-stream, `map-stream` is out of date.

merge2 should work with readable streams.

**Comment by zensh** [comment]
@parsnick I have release v0.3.4 for compat with old-style streams
